### ISSUE TITLE
[QUESTION] Change project name to a better one

### ISSUE THREAD

**Issue by nyxnor** [nyxnor/onionjuggler#19]
OnionService (project) can be easily misunderstood with onion services (hidden services), because of this, the name must change and must differentiate. Also, it has to be related to the utilitites. If you are reading this, you can provide good names also.
For now, I thought of this names:
* `OnionManager` - managing onions
* `OnionOps` - operations with onion services
* `OnionChef` - analogy to cooking onions and being the onion service chef.

**Comment by nyxnor** [comment]
git repo and scripts remain uncapitalized because I prefer no conflics when tipying: onionservice
referring to the project is capitalizing the words OnionService.
But the above is an example, it can't be called like that anymore, a better name that is short and easy.

**Comment by nyxnor** [comment]
* `OnionChopper`

**Comment by radio24** [comment]
OnionJuggler

**Comment by nyxnor** [comment]
@radio24 short description of why juggler? 
![image](https://user-images.githubusercontent.com/69700936/143137138-87284bf6-2e9d-44f2-822d-afe230bc3a6b.png)

**Comment by radio24** [comment]
> @radio24 short description of why juggler?
I don't know if this exists in English, but in German, if someone is dealing with something difficult or delicate, sometimes the word "jonglieren" (juggle) is used.

**Comment by nyxnor** [comment]
@radio24 you have become a juggler
