### ISSUE TITLE
[QUESTION] stem will drop python2.x support

### ISSUE THREAD

**Issue by nyxnor** [nyxnor/onionjuggler#33]
**My doubt is / How can I:**

Keep an eye on stem [git](https://github.com/torproject/stem) and [changelog](https://stem.torproject.org/change_log.html), because the next version will drop python2.x support as it is being [drepecated by python.org](https://www.python.org/doc/sunset-python-2/)

**Comment by radio24** [comment]
Ubuntu dropped Python 2.x support already approx. a year ago. That was why TorBox had to drop wcd as a wireless manager.

**Comment by nyxnor** [comment]
Thank you.
I don't install python by default with OnionJuggler but as `stem 1.8.0` can use python2.x still I support it:
https://github.com/nyxnor/onionjuggler/blob/cc173cfe81681f77021abf0d0284b9ad10c8b483/configure.sh#L95
I let the path for that be chosen on https://github.com/nyxnor/onionjuggler/blob/cc173cfe81681f77021abf0d0284b9ad10c8b483/onionjuggler-cli#L1068
Which is used on https://github.com/nyxnor/onionjuggler/blob/cc173cfe81681f77021abf0d0284b9ad10c8b483/onionjuggler-cli#L1100

**Comment by nyxnor** [comment]
https://github.com/nyxnor/onionjuggler/issues/72
