### ISSUE TITLE
[ENHANCEMENT] Support whiptail as well as dialog for dialog boxes

### ISSUE THREAD

**Issue by nyxnor** [nyxnor/onionjuggler#6]
**My doubt is / How can I:**

@radio24 Have you encountered any problems/incompatibilities translating from `whiptail` to `dialog`? If no, I can make the menu also become a whiptail, else, might have to study to make them compatible in the code.

**Comment by radio24** [comment]
I had the impression that the command lines for `whiptail` and `dialog` are (almost?) the same. For example:

`dialog --clear --backtitle "${BACKTITLE}" --title "${TITLE}" --"${DIALOG_TYPE}" "${MENU}" "$((i+8))" 80 ${i} ${SERVICE_LIST} 2>&1 >/dev/tty)"`

`whiptail --clear --backtitle "${BACKTITLE}" --title "${TITLE}" --"${DIALOG_TYPE}" --separate-output "${MENU}" "$((i+8))" 80 $i ${SERVICE_LIST} 3>&1 1>&2 2>&3"`

Both programs know the `--separate-output` option. However, I had the impression that with `dialog`, it worked without; with `whiptail` it is mandatory to use it, but I'm not sure about it. Also a difference is the `2>&1 >/dev/tty` vs. the `3>&1 1>&2 2>&3` - I don't know if that matters.

**Comment by nyxnor** [comment]
* `--separate-output` - I can include that., From dialog manual
>
> --separate-output
              For certain widgets (buildlist, checklist, treeview), output result one line at a time, with no quoting.  This facilitates parsing by another program.

* Redirection - Yeah, I think it is the same, but it is good to unify them to a single type.

**Comment by nyxnor** [comment]
Redirection is fixed on my local branch.
When you test whiptail (no rush), let me know if it makes a difference using `--separate-output` or not.

**Comment by radio24** [comment]
Ok ... here are the results:
Result with --separate-output: 
```
1
2
x
```
Result without --separate-output: 
"1" "2" "x"

I need --separate-output with the "for in do" loop. Of course, you can manipulate the result without --separate-output in so you can use it with the "for in do" loop.

**Comment by nyxnor** [comment]
This means that if I put ` --separate-output` on dialog for the `checklist`, it becomes compatible with whiptail?

**Comment by radio24** [comment]
`dialog` with `--separate-output` gives the same result as whiptail.
`dialog` without `--separate-output` gives as result: `1 2 x`

**Comment by nyxnor** [comment]
* https://github.com/nyxnor/onionservice/commit/310bb4496babb1239e5069efbdf9a18898bdc742 - add --separate-output to checklist to match dialog with whiptail
* https://github.com/nyxnor/onionservice/commit/9f4da6186ef5eb029a51edc7dc6390552d2f8b4e - start supporting different dialog boxes -> whiptail/dialog 

Ok, start supporting different dialog boxes -> whiptail and dialog.
It is working with dialog but not with whiptail, I don't know why.

**Comment by nyxnor** [comment]
`CHOICE_MAIN=--ok-label: unknown option`

Dialog [man](https://linux.die.net/man/1/dialog)
Whiptail [man](https://linux.die.net/man/1/whiptail)

Dialog: `--ok-label`
Whiptail: `--ok-button`

Why, just why...

**Comment by radio24** [comment]
Argh... the same problem exists with --yes-button --no-button and --cancel-button

**Comment by nyxnor** [comment]
Now need to convert inside the files
```sh
case "${DIALOG_BOX}" in
  dialog)
    YES_FLAG="--yes-label"
    NO_FLAG="--no-label"
    OK_FLAG="--ok-label"
    CANCEL_FLAG="--cancel-label"
    NO_CANCEL_FLAG="--no-cancel"
  ;;
  whiptail)
    YES_FLAG="--yes-button"
    NO_FLAG="--no-button"
    OK_FLAG="--ok-button"
    CANCEL_FLAG="--cancel-button"
    NO_CANCEL_FLAG="--nocancel"
  ;;
esac
```

**Comment by nyxnor** [comment]
Little wip to start accepting whiptail here https://github.com/nyxnor/onionservice/commit/8801b53e1967714e9c2f10394646ad9901c3946e
Still, there is more to do to adjust every dialog box.

**Comment by nyxnor** [comment]
Best solution I found for the height it adding one when it is whiptail, but need to edit every dialog height basically to `"$((current_height+WHIPTAIL_HEIGHT))"`

**Comment by nyxnor** [comment]
db1f257a8579b70110ab2843842ce3363527e9f4
dd63d518f1aef0349ab4cb10d062e8509c62481c
5462753e0daceb0b9e90f7d86ebe0c0fd1b095c9

Ok. As I reviewed all the menu options with caution, I have found and fixed all the bugs that I encountered with. I tested with whiptail and dialog all options and they seem to fit.

This will be kept open for some days in the event a big bug is found.

**Comment by nyxnor** [comment]
Oh, and maybe it is good if you could test if it fits on the tiny lcd screen because I edited some heights to be `"$((i+8+WHIPTAIL_HEIGHT))`

**Comment by nyxnor** [comment]
no bugs so far, closing this.
