### ISSUE TITLE
[QUESTION] Which use case needs two (or more) virtual ports on the same onion address?

### ISSUE THREAD

**Issue by radio24** [nyxnor/onionjuggler#61]
**My doubt is / How can I:**

Which use case needs two (or more) virtual ports on the same onion address and how was this practically implemented? 

The question is relevant because not supporting two or more virtual ports would simplify programming.

**Comment by nyxnor** [comment]
Some server software use different ports for different purposes.
Example is XMPP https://github.com/nyxnor/onioncomms/blob/main/xmpp/prosody/setup.sh#L48-L52
but others like Mumble VOIP only uses one port https://github.com/nyxnor/onioncomms/blob/2771800f97fa08cfe85384f0a007de93c6538234/voip/setup.sh#L32

A website will probably only use one port, the 80 https://github.com/nyxnor/onioncomms/blob/f5820b69ce483095d31c7e231ede868271b29585/tor/README.md#onion-service-example
