### ISSUE TITLE
[QUESTION] Using client authorization in TorBox

### ISSUE THREAD

**Issue by radio24** [nyxnor/onionjuggler#62]
Finally, with [commit ce827fd](https://github.com/radio24/TorBox/commit/ce827fd7c5d39433d828fa6874d903b6466142ae), I added the client authorization to TorBox, meaning that an user of TorBox can add its private key to a `.auth_private` into `/var/lib/tor/onion_auth`. My idea was that if a TorBox user receives the private key that with the client authorization on the TorBox itself, he could access with a client device (e.g. Google Chrome) the Onion Service without entering the private key because the client's traffic is routed through TorBox's tor (see sketch below).

`[Client using .onion in Chrome] -> [TorBox with .auth_private] -> [Onion Service]`

However, it seems that this doesn't work. 

My questions are:
- Did you already test tor's client authorization in a similar setting. 
- Is there a way I can use the authorization of a "tor router" for the clients, or is this only for local authorization (meaning on the device with tor itself on it)? I
- In case I don't use a graphical user interface, how can I use the client authorization?

**Comment by nyxnor** [comment]
I only use the Tor Browser when using Tor, but as you are using Chrome, then as the popup will not appear on the browser, you need to configure on the TorBox the client private key. The pop up was only implemented by Tor Browser, that is why.

On a note of similar setting, yes, I've used by configured on Whonix Gateway, in association with the TorBox router.
https://www.whonix.org/wiki/Onion_Services#Onion_Service_Authentication_Client_Setup

So after you test this configuring the client auth on the tor daemon, let me know.
Of if you try to do this on Tor Browser that is getting the connection directly form TorBox, also let me know.
But any other Browser that is not TBB is not gonna work.

**Comment by radio24** [comment]
To be clear: Chrome (and the TorBrowser) are running on a client device (e.g. Macbook) of the TorBox. The private client key is configured on the TorBox on whom the tor daemon is running.

Based on the failed tests, I assume that the private client key has to be on the client device (Macbook), and it will not work if it is on the TorBox. Although the data from the client device is routed through TorBox to the tor network, most likely, the tor daemon on the TorBox doesn‘t know if one of the clients needs an authorisation for an Onion Service. In my test, it doesn‘t work (if I didn‘t do something wrong) in such configuration - Chrome cannot access it, and the TorBrowser is still showing the popup.

**Comment by nyxnor** [comment]
I didn't test this this way yet, I will see if I can do it this week but no promise.

**Comment by nyxnor** [comment]
Not reproducible for me. I didn't test with TorBox specifically, but with a similar setting.

First I tested with sys-whonix (Gateway/TorBox) and anon-whonix (Workstation/client), but as there may be some inner networking configuration, I use a normal debian vm with sys-whonix as the gateway, so it is similar to TorBox.

So imagine sys-whonix is TorBox and client-test is the debian client.
I added the client private key to ClientOnionAuthDir/client.auth_private and the public key is automatically added by the script to HiddenServiceDir/authorized_clients/client.auth.

sys-whonix is only providing network to the client-test vm, it does not have any special configuration.

Can you retry the steps? I've tested some times now and seem to be working.
Also, are you using tor only from the torbox and not from the client?
Maybe this solves it for TorBrowser? https://github.com/radio24/TorBox/blob/master/install/start_tor_browser_on_macos.sh

Just as a note, at first it was not working for like 20, 30 minutes on client-test Chromium, but it was working on anon-whonix TorBrowser. But then it start working on chromium suddenly.

**Comment by radio24** [comment]
Will re-test it with a 30 minutes waiting periode.

**Comment by nyxnor** [comment]
Steps:
- Enable service on TorBox
- Enable site on TorBox
- `curl site.onion` to test its reachability
- Access site on MacOS using TorBrowser
- Enable server side authentication
- Try to access service and fail
- Add client side authentication to TorBox
- Succeed hopefully

**Comment by radio24** [comment]
I appreciate your help. Waiting about 30 minutes solved the problem. Using TorBox with a private key in the _ClientOnionAuthDir_ will give the TorBox itself access, and all client devices whose data traffic is routed through the TorBox. This feature is implemented with the [commit 05fdb5e](https://github.com/radio24/TorBox/commit/05fdb5e73b892bc6d98482874953a1a962fbb6a0) and will be part of the upcoming TorBox v.0.5.2.
